AWX:
  # enable use of awx-deploy template
  enabled: false
  name: awx
  spec:
    admin_user: admin

  # configurations for external postgres instance
  postgres:
    enabled: true
    host: pgforawx.postgres.database.azure.com
    port: 5432
    dbName: postgres
    username: pgadmin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Ansible#123
    sslmode: prefer
    type: unmanaged
