---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-configuration-secret
  namespace: awx
secretGenerator:
  - name: awx-postgres-configuration-secret
    type: Opaque
    literals:
      - host=pgforawx.postgres.database.azure.com
      - port=5432
      - database=postgres
      - username=pgadmin
      - password=Ansible#123
      - sslmode=prefer
      - type=unmanaged
