# {{- if and $.Values.AWX.enabled $.Values.AWX.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration-secret
  namespace: awx
stringData:
  host: pgforawx.postgres.database.azure.com
  port: 5432
  database: postgres
  username: pgadmin
  password: Ansible#123
  sslmode: prefered
  type: unmanaged
type: Opaque
# {{- end }}
# {{- end }}
